CREATE TABLE `users` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `cedula` VARCHAR(15) NOT NULL UNIQUE COMMENT 'Must be varchar to preserve leading zeros',
  `role` ENUM('ADMIN', 'REVISOR') DEFAULT 'REVISOR',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `expedientes` (
  `id` VARCHAR(50) PRIMARY KEY,
  `nombre` VARCHAR(255) NOT NULL,
  `status` ENUM('PENDIENTE', 'EN_REVISION', 'CON_OBSERVACIONES', 'CORREGIDO', 'CONFIRMADO') DEFAULT 'PENDIENTE',
  `revisor_id` INT COMMENT 'Foreign Key pointing to users table',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`revisor_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE `expediente_logs` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `expediente_id` VARCHAR(50),
  `author_id` INT COMMENT 'Who made the change',
  `previous_status` ENUM('PENDIENTE', 'EN_REVISION', 'CON_OBSERVACIONES', 'CORREGIDO', 'CONFIRMADO'),
  `new_status` ENUM('PENDIENTE', 'EN_REVISION', 'CON_OBSERVACIONES', 'CORREGIDO', 'CONFIRMADO'),
  `comentario` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`expediente_id`) REFERENCES `expedientes`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB;